### ISSUE TITLE
수학1-2(소수, 소인수분해, 팩토리얼), 수학2-1(제곱, 행렬, 피보나치의 수, 이항계수, 파스칼의 삼각형)

### ISSUE THREAD

**Issue by kdomo** [Green-Record/algorithm-study#10]
# 수학1-2(소수, 소인수분해, 팩토리얼)

- 1~N 까지의 수에서 모든 소수를 구하는 방법 '에라토스테네스의 체'의 개념
- 소인수분해의 개념과 간단한 풀이법

https://www.acmicpc.net/problem/2089
https://www.acmicpc.net/problem/11576
https://www.acmicpc.net/problem/1978
https://www.acmicpc.net/problem/1929
https://www.acmicpc.net/problem/6588
https://www.acmicpc.net/problem/11653
https://www.acmicpc.net/problem/10872
https://www.acmicpc.net/problem/1676
https://www.acmicpc.net/problem/2004

# 수학2-1(제곱, 행렬, 피보나치의 수, 이항계수, 파스칼의 삼각형)
- 분할정복을 이용하여 제곱을 구하는 방법
- 이진수의 원리를 이용하여 제곱을 구하는 방법
- 행렬의 곱 구하기
- 피사노 주기의 개념과 구하는 방법
- 음수 번째의 피보나치의 수에 대한 규칙성
- 이항계수 구하는 방법

https://www.acmicpc.net/problem/1629
https://www.acmicpc.net/problem/2738
https://www.acmicpc.net/problem/2740
~https://www.acmicpc.net/problem/10830~
https://www.acmicpc.net/problem/2747
https://www.acmicpc.net/problem/2748
~https://www.acmicpc.net/problem/2749~
~https://www.acmicpc.net/problem/11444~
https://www.acmicpc.net/problem/10826
https://www.acmicpc.net/problem/10870
https://www.acmicpc.net/problem/1788
https://www.acmicpc.net/problem/9471
~https://www.acmicpc.net/problem/2086~
~https://www.acmicpc.net/problem/11440~
~https://www.acmicpc.net/problem/11442~
~https://www.acmicpc.net/problem/11443~
~https://www.acmicpc.net/problem/11778~
~https://www.acmicpc.net/problem/11050~
https://www.acmicpc.net/problem/11051
~https://www.acmicpc.net/problem/11402~
~https://www.acmicpc.net/problem/11439~

**Comment by jinjinhee** [comment]
# 소수, 소인수분해, 팩토리얼
## 1~N 까지의 수에서 모든 소수를 구하는 방법
### '에라토스테네스의 체'의 개념
```
에라토스테네스의 체는 가장 먼저 소수를 판별할 범위만큼 배열을 할당하여, 해당하는 값을 넣어주고, 이후에 하나씩 지워나가는 방법을 이용한다.

배열을 생성하여 초기화한다.
2부터 시작해서 특정 수의 배수에 해당하는 수를 모두 지운다.(지울 때 자기자신은 지우지 않고, 이미 지워진 수는 건너뛴다.)
2부터 시작하여 남아있는 수를 모두 출력한다.
```
```
def prime_list(n):
    # 에라토스테네스의 체 초기화: n개 요소에 True 설정(소수로 간주)
    sieve = [True] * n

    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           # i가 소수인 경우 
            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
                sieve[j] = False
```
![image](https://user-images.githubusercontent.com/44153167/197816336-1559a760-1e92-4467-9231-d7b7219f1ff4.png)

## 소인수분해의 개념과 간단한 풀이법
---
# 제곱, 행렬, 피보나치의 수, 이항계수, 파스칼의 삼각형
### 파스칼의 삼각형
![image](https://user-images.githubusercontent.com/44153167/197765118-4ff80fe0-3bf5-439f-8f83-cc26cee0a3e1.png)
![image](https://user-images.githubusercontent.com/44153167/197765201-df4bc385-ea2a-402d-b5b2-7eaad55c47dd.png)


## 분할정복을 이용하여 제곱을 구하는 방법
```
지수 법칙
A^m+n = A^m x A^n
나머지 분배 법칙
(AxB)%C = (A%C) *(B%C) % C
```
```
def power(a, n):
    if n == 0:
        return 1
    
    x = power(a, n//2)

    if n % 2 == 0:
        return x * x
    
    else:
        return x * x * a
```
## 이진수의 원리를 이용하여 제곱을 구하는 방법
## 비트연산자
![image](https://user-images.githubusercontent.com/44153167/197816812-eb1c7a30-58a5-4488-a587-aea3af82282c.png)

```
예시
a=69(1000101), b=15(0001111)

a & b = 12 → 0b0000101
a \| b = 79 → 0b1001111
a ^ b = 74 → 0b1001010
~b = -16 -0b10000
b << 2 =60 → 111100
a >> 3 = 8 → 1000
```

## 행렬의 곱 구하기
![image](https://user-images.githubusercontent.com/44153167/197730214-6ad85ce5-7d2a-43ce-ad40-63d5c6317d80.png)

## 피사노 주기의 개념과 구하는 방법
### 피사노 주기(Pisano period)
- 개념
 피보나치 수를 어떤 수 K로 나눌 때, 나머지는 항상 주기를 가지게 되는데 이를 피사노 주기라고 한다.
- 구하는 법
```
def Pisano_period(num):
  answer = 1
  mod1, mod2 = 1, 2
  while True:
    if mod1 % num == 1 and mod2 % num == 1:
      break
    answer += 1
    mod1, mod2 = mod2, (mod1 + mod2) % num
  return answer
```
## 음수 번째의 피보나치의 수에 대한 규칙성
### 피보나치 수열 정의
![image](https://user-images.githubusercontent.com/44153167/197817042-a35eca5a-7fad-4665-b126-97c39cce870c.png)
### 음수 번쨰
```
짝수 번째(ex. -2, -4...): 양의 홀수 번째에 -1을 곱한 값
ex) F(-2)=-F(2)=-1
홀수 번째(ex. -1, -3...): 양의 홀수 번째와 동일
ex) F(-1)=F(1)=1
```
## 이항계수 구하는 방법
- 이항계수
이항계수(Binomial Coefficient)는 조합론에서 등장하는 개념으로 주어진 크기 집합에서 원하는 개수만큼 순서없이 뽑는 조합의 가짓수를 일컫는다.
![image](https://user-images.githubusercontent.com/44153167/197694187-4c50515e-957d-4eca-ac66-dbc031dc7131.png)

**Comment by kdomo** [comment]
# 에라토스테네스의 체
- 가장 대표적인 소수 판별 알고리즘.
- 소수가 되는 수의 배수를 지우면 남은 건 소수가 된다는 알고리즘
- 소수(Prime)이란 양의 약수를 1과 자기자신만 가지고 있는 자연수.
- 대량의 소수를 빠르게 구하는 방법

일반적인 소수 판별 코드

시간복잡도 : O( $N^2$ )
```java
boolean isOK;
for(int i=start;i<=end;i++) {
    isOK = true;
    for(int j=2;j<=i;j++) { // i 까지 루프
        if(i % j == 0) {
            isOK = false;
            break;
        }
    }
    if(isOK && i != 1) System.out.println(i);
}
출처: https://mygumi.tistory.com/66 [마이구미의 HelloWorld:티스토리]
```
위의 코드처럼 작성한다면 2부터 자신의 수까지 루프를 돌면서 나머지 연산을 진행한다.
데이터가 커지면 커질수록 루프 횟수도 그만큼 증가한다.

그렇기에 에라토스테네스의 체를 통해
소수가 되는 수의 배수를 지우고 남은 소수만을 알기위한 코드
```java
int rootSqrt = (int) Math.sqrt(n);
for(int i=2;i<=rootSqrt;i++) {
    if (array[i]) {        // 이미 걸려진 수의 배수는 skip
        continue;
    }
    for(int j=i+i;j<=1000000;j+=i) {
        array[j] = true;
    }
}
출처: https://mygumi.tistory.com/66 [마이구미의 HelloWorld:티스토리]
```

# 소인수 분해
- 자연수를 소인수의 곱으로 나타낸 것
```java
for(int i = 2; i <= N; i++) {
	while(N % i == 0) {
		println(i);
		N /= i;
	}
}
```

---

# 분할정복을 이용하여 제곱을 구하는 방법
- 거듭제곱의 계산
  - 어떤 수를 n번 곱하여 거듭제곱을 구현 가능하다. 하지만 n번 곱하기 때문에 시간 복잡도는 O( $N$ )이 걸린다
- 개선된 거듭 제곱의 계산
  - 거듭 제곱을 분할정복을 기반으로 시간 복잡도를 O( $logN$ )까지 줄일 수 있다.
```java
private static long pow(long a, long b) {
		// 지수가 0인 경우(종료 조건).
		if (b == 0) {
			return 1;
		}

		// 반으로 나눈 거듭제곱 계산.
		long res = pow(a, b / 2);

		// 지수가 짝수인 경우.
		if (b % 2 == 0) {
			return res * res;
		}
		// 지수가 홀수인 경우
		else {
			return res * res * a;
		}
	}
```

**Comment by thankyouthankyou** [comment]
# 에라토스테네스의 체
1.	1~N 까지의 수에서 모든 소수를 구하는 방법으로써 소수인지 판별하는 방법과는 구분 된다.
	특정 범위가 주어지고 그 범위 내의 모든 소수를 찾아야 하는 경우 다른 방법이 없다.
	즉, 임의의 수 N까지 소수를 구하고자 할 때 2부터 N의 제곱근까지 돌며 모든 배수들을 소수에서 제외시키는 방식이다.
	1.	1~N 까지 숫자를 모두 나열한다.
	1.	소수도, 합성수도 아닌 자연수 1을 제거한다.
	1.	2를 제외한 2의 배수를 제거한다.
	1.	3을 제외한 3의 배수를 제거한다.
	1.	4의 배수는 지울 필요 없다.(2의 배수에서 이미 지워졌다)
	1.	5를 제외한 5의 배수를 제거한다.
	1.	7을 제외한 7의 배수를 제거한다.
	1.	8의 배수는 지울 필요 없다.(2의 배수)
	1.	9의 배수는 지울 필요 없다.(3의 배수)
	1.	10의 배수는 지울 필요 없다.(2의 배수)
	1.	11이상의 소수들의 배수부터는 11> 10의 제곱근 이므로 지울 필요 없다.
	

		    #include <iostream>
		    #include <cmath>

		    using namespace std;
		
		    int number = 100;
		    int primeNum[100];

		    void GetPrimeNum()
		    {
			    for(int i=2; i <=number; i++)
			    {
				    primeNum[i] = i;
			    }

			    for(int i=2; i<=sqrt(number); i++)
			    {
				    if(primeNum[i] == 0)
				    continue;

				    for(int j = i*i; j <= number; j+=i)
				    {
				        primeNum[j] = 0;
			            }
			for(int i = 2; i <= number; i++)
			{
				if(primeNum[i] != 0;
					cout << primeNum[i];
		       }
		      int main()
		     {
			  GetPrimeNum();
		     }

**Comment by jonggking** [comment]
## 소수, 소인수분해, 팩토리얼    

### 에라토스테네스의 체
1. 2부터 𝑁까지의 모든 자연수를 나열한다
2. 남은 수 중에서 아직 처리하지 않은 가장 작은 수 𝑖를 찾는다
3. 남은 수 중에서 i의 배수를 모두 제거한다(𝑖는 제거하지 않는다)
4. 더 이상 반복할 수 없을 때까지 2번과 3번의 과정을 반복한다
```
import math

n = 1000 # 2부터 1,000까지의 모든 수에 대하여 소수 판별
array = [True for i in range(n + 1)] # 처음엔 모든 수가 소수(True)인 것으로 초기화

# 에라토스테네스의 체 알고리즘 
for i in range(2, int(math.sqrt(n)) + 1): # 2부터 n의 제곱근까지의 모든 수를 확인하며
    if array[i] == True: # i가 소수인 경우 (남은 수인 경우)
        # i를 제외한 i의 모든 배수를 지우기
        j = 2 
        while i * j <= n:
            array[i * j] = False
            j += 1

# 모든 소수 출력
for i in range(2, n + 1):
    if array[i]:
        print(i, end=' ')
```

## 제곱, 행렬, 피보나치의 수, 이항계수, 파스칼의 삼각형
### 행렬
```
배열의 황제! Numpy

np.array - 배열생성
np.zeros - 0이 들어있는 배열 생성
np.ones - 1이 들어있는 배열 생성
np.empty - 초기화되어 있지 않은 값이 들어있는 배열 반환
np.arange(n) - 배열 버전의 range 함수
```
   
### 이항계수
: n개의 서로다른 것 들 중에서 k 개를 선택하는 것의 조합(combination)의 경우의 수
   
### 파스칼의 삼각형   
   
![image](https://user-images.githubusercontent.com/108375964/197742611-9296c065-5f65-48ed-9fd0-b67dd84a614a.png)
**파스칼의 삼각형 특징**    
숫자들의 의미 = 위쪽 수열의 합과 같습니다.
![image](https://user-images.githubusercontent.com/108375964/197746639-9a0f1f5f-5b04-4d2d-b963-7bafbd783180.png)
n행의 수열 = n가지의 물건 중 순서 없이 물건을 뽑는 가짓 수 
![image](https://user-images.githubusercontent.com/108375964/197746952-8eae17e8-9649-40a1-9bd2-803eda37e074.png)

**Comment by josuehyeon** [comment]
- 에라토스테네스의 체
수학에서 에라토스테네스의 체는 소수를 찾는 방법이다. 고대 그리스 수학자 에라토스테네스가 발견하였다.

N 의 소수를 구할때
i^2 > N이면
 2~(i-1) 까지 수의 배수를 제외한 수
​
public class Eratos {
	public static void main(String[] args) {
		// ArrayList로 구현
		ArrayList<Boolean> primeList;

		// 사용자로부터의 콘솔 입력
		Scanner scan = new Scanner(System.in);
		int n = scan.nextInt();

		// n <= 1 일 때 종료
		if(n <= 1) return;

		// n+1만큼 할당
		primeList = new ArrayList<Boolean>(n+1);
		// 0번째와 1번째를 소수 아님으로 처리
		primeList.add(false);
		primeList.add(false);
		// 2~ n까지 소수로 설정
		for(int i=2; i<=n; i++ )
			primeList.add(i, true);

		// 2부터  ~ i*i <= n
		// 각각의 배수들을 지워간다.
		for(int i=2; (i*i)<=n; i++){
			if(primeList.get(i)){
				for(int j = i*i; j<=n; j+=i) primeList.set(j, false);
				//i*i 미만은 이미 처리되었으므로 j의 시작값은 i*i로 최적화할 수 있다.
			}
		}
		StringBuffer sb = new StringBuffer();
		sb.append("{");
		for(int i=0; i<=n; i++){
			if(primeList.get(i) == true){
				sb.append(i);
				sb.append(",");
			}
		}
		sb.setCharAt(sb.length()-1, '}');

		System.out.println(sb.toString());

	}
}
