### ISSUE TITLE
수학2-2(카탈란 수, 오일러 피 함수, 유클리드 알고리즘, 나머지 연산, 순열)

### ISSUE THREAD

**Issue by jonggking** [Green-Record/algorithm-study#18]
# 수학2-2(카탈란 수, 오일러 피 함수, 유클리드 알고리즘, 나머지 연산, 순열)
관련 문제들
https://www.acmicpc.net/problem/10422
https://www.acmicpc.net/problem/11689
<s>https://www.acmicpc.net/problem/11661</s>
https://www.acmicpc.net/problem/11401
https://www.acmicpc.net/problem/10972
https://www.acmicpc.net/problem/10973
https://www.acmicpc.net/problem/10974
https://www.acmicpc.net/problem/1722
+ [지난주에 안푼 문제](https://github.com/Green-Record/algorithm-study/issues/10)

- 카탈란 수의 개념과 적용 사례
- 카탈란 수 구하는 방법
- 오일러 피 함수의 개념과 활용
- 오일러 피 함수 구하는 방법
- 사전순으로 다음에 오는 순열

**Comment by jinjinhee** [comment]
(작성 중)
# 카탈란 수

## 개념과 적용 사례
조합론에서의 개수 세기 문제 가운데 많은 것이 카탈랑 수를 그 해로 갖는다.

## 카탈란 수 구하는 방법
Cn은 n x n 격자의 왼쪽 아래 꼭지점 (0, 0)에서 오른쪽 위 꼭지점 (n, n)을 향해 최단거리로 이동하는 경우의 수 중 직선 y = x를 넘어가지 않는 경우의 수와 같다.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/44153167/198869374-f4b5f40b-e450-43e5-be6a-69b367213a49.png">

<img width="224" alt="image" src="https://user-images.githubusercontent.com/44153167/198869269-43f9f580-6225-4292-88b8-41e4c9b29763.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/44153167/198869240-3f80f4c8-dc13-48da-9b9b-11fd48ee7246.png">

---
# 오일러 파이 함수
##개념과 활용
φ(n) = (n이하의 자연수 중에서 n과 서로소인 것의 개수)
## 오일러 피 함수 구하는 방법
![image](https://user-images.githubusercontent.com/44153167/198869640-581e7ae5-8dd4-43b7-85eb-ac3dcb881eeb.png)

# 사전순으로 다음에 오는 순열
??
# 페르마의 소정리
p가 소수, a가 정수일 때
![image](https://user-images.githubusercontent.com/44153167/199277151-6f457304-9da9-4d67-93ee-a017cad5c967.png)
p가 소수이고 a와 p가 서로소이면 ap-1≡1(mod p)이다.

# 나머지 연산(모듈로 연산)의 분배법칙

```
(A + B) % p = ((A % p) + (B % p)) % p

(A x B) % p = ((A % p) x (B % p)) % p

(A - B) % p = ((A % p) - (B % p) + p) % p
```

**Comment by jiyun828** [comment]
<h1> 카탈란 수

<h2>개념, 적용사례, 구하는법
<h5>
n번째 카탈란 수(Catalan number) 이란 아래의 점화식을 만족하는 수열의 번째 항을 말한다.

C0=1

이 수열의 첫 10개 항을 나열하면 다음과 같다. (C0부터 C9까지)
 
1, 1, 2, 5, 14, 43, 132, 429, 1430, 4862, ···

카탈란 수는 조합론(Combinatorics)에서 빈번하게 등장하는 수 중의 하나로, 아래와 같은 문제들의 해답이 모두 n번째 카탈란 수 Cn으로 주어진다. 먼저 C4= 14 라는 사실을 기억하자.


Cn은 n쌍의 여는 괄호와 닫는 괄호로 만들 수 있는 올바른 괄호 구조의 가짓수와 같다. 예를 들어 4쌍의 열린 괄호는 아래의 14가지 경우의 수가 나온다.

(((()))), (())(()), (()()()), ()((())), ()(()()), ()()(()), (()(())),

()()()(), ((()())), ()(())(), ((()))(), (()())(), (())()(), ((())())


Cn은 n+1개의 항에 이항연산을 적용하는 순서의 가짓수와 같다. 예를 들어 5개의 문자 a, b, c, d, e에 괄호로 이항연산의 순서를 표현하면 아래의 14가지 경우가 나온다.

(((ab)c)d)e, ((ab)(cd))e, (ab)((cd)e), ((ab)c)(de),

a(b(c(de))), a((bc)(de)), (a(bc))(de), (ab)(c(de)),

((a(bc))d)e, (a((bc)d))e, a(((bc)d)e), a(b((cd)e)),

a((b(cd))e), (a(b(cd)))e


Cn은 n+2각형을 n개의 삼각형으로 나누는 방법의 개수이다. 아래 그림은 6각형을 4개의 삼각형으로 나누는 14가지 경우를 모두 나타낸 것이다.



(출처 - Wikipedia)
 

Cn은 n x n 격자의 왼쪽 아래 꼭지점 (0, 0)에서 오른쪽 위 꼭지점 (n, n)을 향해 최단거리로 이동하는 경우의 수 중 직선 y = x를 넘어가지 않는 경우의 수와 같다. 4 x 4 격자에서 가능한 14가지 경우를 아래 그림처럼 나타낼 수 있다.



(출처 - Wikipedia)
 

Cn은 높이가 n인 계단 모양을 n개의 직사각형으로 완전히 채울 수 있는 경우의 수와 같다. 예를 들어, 높이 4인 계단 모양을 n개의 직사각형으로 채우면 다음의 14가지 경우가 나온다.

 Cn은 n + 1개의 단말 노드를 갖는 이진 순서 트리의 개수


(출처 - Wikipedia)


<h2> 증명
<h5>예제)
입장료가 500원인 전시회에 6명의 학생들이 입장하려고 한다. 이들 가운데 3명은 1000원짜리 지폐를 한 장씩 갖고 있고, 나머지 3명은 500원짜리 동전을 한 개씩 갖고 있다. 맨 처음 표를 판매할 때 매표소에는 잔돈이 없기 때문에 잔돈을 내어줄 수 없고, 표는 한 사람이 한 장만 살 수 있다고 한다. 모든 사람들이 순조롭게 표를 사고 매표소 직원은 잔돈을 내주지 못해 어려움을 겪지 않도록 입장하는 방법의 수를 구하여라. (단, 같은 돈을 들고 있는 사람끼리 자리를 바꾸는 것은 동일한 경우로 본다.)<br><br> 

사람을 구별ㅇ하지 않으므로, 500원짜리 동전을 가진 사람을 a, 1000원짜리 지폐를 가진 사람을 b라 할 수 있다. 입장하는 경우 어느 a에 대해서도 그 앞에 a의 개수보다 b의 개수가 더 많아서는 안 된다. 입장할 수 없는 예로 abbaba의 경우 세 번째 b의 앞에는 a와 b의 개수가 같음을 알 수 있다.<br> 만약 그 b까지의 a와 b를 바꾼다면(baaaba) a 4개와 b 2개의 나열이 된다. 그렇다면 반대로 a 4개와 b 2개를 나열하는 모든 경우에 대하여 a가 더 많아지는 위치까지의 a와 b를 바꾼다면 바로 입장할 수 없는 경우가 될 것이다. 예를 들어 babaaa의 경우 ababba이 된다.
<br>따라서 구하고자 하는 경우의 수는 6!/3!3! - 6!/4!2! = 5가 된다.


<h1> 오일러 파이 함수

<h2>개념, 활용, 구하는 방법

<h5>
오일러 파이 함수= "임의의 양의 정수 m에 대하여, m 이하의 양의 정수 중 m과 서로소인 양의 정수의 개수"를 함수값으로 갖는 함수

<br>

<h2>응용
<h5>
응용
오일러 피 함수는 수학의 다양한 분야에서 등장한다. 예를 들어, 군론에서는 순환군 {\displaystyle \mathbb {Z} /n\mathbb {Z} }{\mathbb  Z}/n{\mathbb  Z}의 가능한 생성원(generator)의 수는 {\displaystyle \phi (n)}\phi (n)이다. 이는 {\displaystyle n}n과 서로소인 임의의 수를 사용하여 {\displaystyle \mathbb {Z} /n\mathbb {Z} }{\mathbb  Z}/n{\mathbb  Z}를 생성할 수 있기 때문이다.

또한, 정n각형이 작도 가능한 다각형인지, 즉 눈금없는 자와 컴퍼스만으로 작도할 수 있는지는 {\displaystyle \phi (n)}\phi (n)이 2의 거듭제곱수인지와 동치이다. 즉,

n = 2, 3, 4, 5, 6, 8, 10, …
이라면


phi (n) = 1, 2, 2, 4, 2, 4, 4, …
이므로 정n각형을 작도할 수 있지만, 다른 값의 경우에는 작도할 수 없다. 특히, n이 소수인 경우를 페르마 소수라고 한다.

오일러 피 함수는 암호학의 RSA 암호에서도 핵심적인 역할을 한다.

**Comment by jonggking** [comment]
# 카탈란 수의 개념과 적용 사례
### 개념
-------
![image](https://user-images.githubusercontent.com/108375964/200465824-9c4b622e-f9ea-4f5b-8b0a-3f5fd228c3ed.png)

n번째 카탈란 수(Catalan number) Cn이란 위의 점화식을 만족하는 수열의 n번째 항.
1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862, ···
   
### 적용사례
- Cn은 n쌍의 여는 괄호와 닫는 괄호로 만들 수 있는 올바른 괄호 구조의 가짓수와 같다. 
![image](https://user-images.githubusercontent.com/108375964/199184633-11ee782c-b2c6-48bd-8890-480d6b58216e.png)
- Cn은 n+2각형을 n개의 삼각형으로 나누는 방법의 개수이다. 아래 그림은 6각형을 4개의 삼각형으로 나누는 14가지 경우를 모두 나타낸 것이다
![image](https://user-images.githubusercontent.com/108375964/199184256-874690e6-d9ff-4331-8d15-03386847f14e.png)
-Cn은 n x n 격자의 왼쪽 아래 꼭지점 (0, 0)에서 오른쪽 위 꼭지점 (n, n)을 향해 최단거리로 이동하는 경우의 수 중 직선 y = x를 넘어가지 않는 경우의 수와 같다. 4 x 4 격자에서 가능한 14가지 경우를 아래 그림처럼 나타낼 수 있다.
![image](https://user-images.githubusercontent.com/108375964/199185191-0a3686a7-8296-4eee-a6c4-16232ce96bfd.png)

# 카탈란 수 구하는 방법
모든 n≥0에 대하여, 카탈란 수(Catalan number) Cn은 아래 식을 만족.
![image](https://user-images.githubusercontent.com/108375964/199185439-c0034c94-9ff9-4fdf-8d48-0fe61a6ddad4.png)
   
# 오일러 피 함수의 개념과 활용
### 개념 
자신보다 작은 양수 중에서 자기 자신과의 최대 공약수가 1인 숫자가 몇 개인지를 나타냄. 
따라서 소수 p의 경우 모든 숫자가 서로 소 이기 때문에 다음과 같이 쓸 수 있음
φ(p) = p - 1
그리고 p와 q가 서로 소인 경우 다음과 같은 식이 성립.
φ(pq) = φ(p)φ(q)


# 오일러 피 함수 구하는 방법
p가 소수라면, pk와 서로소가 아닌 수들은 반드시 p를 인수로 가져야 합니다. 1부터 pk까지의 수 중 이런 수들은 pk/p=pk−1개가 있습니다. 따라서 다음 결론을 얻습니다.
![image](https://user-images.githubusercontent.com/108375964/199205778-c2d4b6cc-8907-43fd-bff9-9a8ec347223a.png)
따라서 모든 수는 소수의 곱으로 나타낼 수 있으므로, 소인수분해를 한 뒤 오일러 파이 함수가 곱셈적 함수임을 이용해서 계산.
![image](https://user-images.githubusercontent.com/108375964/199205861-52c3b7f0-9d4a-486b-b154-4295fa6864f0.png)

**Comment by kdomo** [comment]
## 카탈란 수 
- 조합론에서 카탈란 수는 이진 트리의 수 따위를 셀 때 등장하는 수열이다.
- 기호로는 $Cn$
- 카탈란 수를 적용 할 수 있는 문제
  - 경로의 수 문제
    - 최단경로의 경우의 수
  - 한 요소가 다른 요소보다 항상 크게 유지하는 문제
    - 같은 개수의 X와 Y를 활용해 만드는 단어 중 단어의 처음에서 X와 Y의 개수를 셌을 때 항상 X의 개수가 Y의 개수 이상인 단어의 개수를 구하는 문제
  - 괄호 열고 닫기 문제
    - n개 쌍의 괄호를 쌍이 맞도록 열고 닫는 방법의 수를 구하는 문제
  - 다각형 나누기 문제
    - n+2각형을 n개의 삼각형으로 나누는 방법의 수를 구하는 문제

## 카탈란 수 구하는 방법
- 1.재귀함수를 통한 카탈란의 수 구하기
  - 카탈란의 수 점화식 이용 : sum { i=0 ~ (n-1) }  $Cn = (Ci * Cn-i-1)$
  - n이 커지면 시간복잡도가 커진다.
```java
public long getCatalan(int n){
    int res = 0;

    if (n <= 1) {
        return 1;
    }
    for (int i = 0; i < n; i++) {
        res += getCatalan(i) * getCatalan(n - i - 1);
    }
    return res;
}
```
- 2.반복문을 통한 카탈란의 수 구하기
  - 카탈란의 수 점화식 이용 : sum { i=0 ~ (n-1) }  $Cn = (Ci * Cn-i-1)$
  - 여는 괄호와 닫는 괄호가 n이고, n의 최대값이 MAX일 때
```java
static long getCatalan2(int n){
    long d[] = new long[MAX + 1];
    d[0] = 1; // C0 = 1

    // EX) C4 = C0C3 + C1C2 + C2C1 + C3C0
    for (int i = 1; i <= MAX; i++){
        d[i] = 0;

        for(int j = 0; j < i; j++){
            d[i] += d[j] * d[i-1-j];
            d[i] %= MOD;
        }
        d[i] %= MOD;
    }
    return d[n];
}
```

## 오일러 피 함수
### 오일러 피 함수란?
  - 1 ~ n 까지의 양의 정수 중 n과 서로소인 수의 개수를 구하는 것
  - 1, 2, 3, 4, 5, 6, 7, 8, 10, 11 중에, 11이외에는 모두 11과 서로소이다. 그러므로 11-1=10 따라서, φ(11) = 10
### 서로소란?
  - 1 이외에 공약수를 갖지 않는 둘 이상의 양의 정수를 말한다. 이를테면 7과 13은 서로소이다.
### 오일러 피 함수의 성질
  - 소수 p의 경우 오일러 파이 함수의 값은 φ(p) = p-1 이다.
  - 일반적으로 φ는 곱셈적 함수다. 즉 , m, n이 서로소인 정수 일 때 φ(mn) = φ(m) φ(n)이다.
### 오일러 피 함수의 활용
  - 정n각형이 작도 가능한 다각형인지, 즉 눈금없는 자와 컴퍼스만으로 작도할 수 있는지는 φ(n)이 2의 거듭제곱수인지와 동치이다.
  - 또한 오일러 피 함수는 암호학의 RSA 암호에서도 핵심적인 역할을 한다.

## 오일러의 피 함수 구하는 방법
```java
long res = n;

for (long i = 2; i * i <= n; i++) {
    if (n % i == 0) {
        while (n % i == 0) {
            n /= i;
        }
        res -= res / i;
    }
}

if (n > 1) {
    res -= res / n;
}

return res;
```

## 사전순으로 다음에 오는 순열
```
1. A[i-1] < A[i]를 만족하는 가장 큰 i를 찾는다. (즉, 순열의 마지막 수에서 끝나는 가장 긴 감소수열을 찾는다.)
2. j>=i 이면서 A[j] > A[i-1]를 만족하는 가장 큰 j를 찾는다.
3. A[i-1]과 A[j]를 swap한다.
4. A[i]부터 순열을 뒤집는다.
```

## 사전순으로 다음에 오는 순열 구하는 방법
```java
 // 1. A[i-1] < A[i]를 만족하는 가장 큰 i를 찾는다.
// (즉, 순열의 마지막 수에서 끝나는 가장 긴 감소수열을 찾는다.)
int i = arrays.length - 1;
while (i > 0 && arrays[i-1] >= arrays[i])
    i--;

// 마지막 순열 (이미 사전순으로 정렬된 상태, 전체가 감소수열)
if (i <= 0)
    return false;

// 2. j>=i 이면서 A[j] > A[i-1]를 만족하는 가장 큰 j를 찾는다.
int j = arrays.length - 1;
while (arrays[j] <= arrays[i-1])
    j--;

// 3. A[i-1]과 A[j]를 swap한다.
int tmp;
tmp = arrays[i-1];
arrays[i-1] = arrays[j];
arrays[j] = tmp;

// 4. A[i]부터 순열을 뒤집는다.
int k = arrays.length - 1;
while (i < k) {
    tmp = arrays[i];
    arrays[i] = arrays[k];
    arrays[k] = tmp;
    i++;
    k--;
}
return true;
```

**Comment by josuehyeon** [comment]
- 카탈란의 수
  -  Cn,은 (0, 0)을 출발하여 x>=y 를 만족하는
정숫점(격자점)을 지나 (n, n)에 이르는 경로의 갯수

![image](https://user-images.githubusercontent.com/76567405/199220325-445cbe52-7054-4715-bff8-d365fda6c464.png)
참고 https://plusthemath.tistory.com/433

- 오일러 피(파이) 함수
   - φ(n)는 1부터 n까지 정수 중 n과 서로소인 수의 개수를 세는 함수

![image](https://user-images.githubusercontent.com/76567405/199218370-1bca921a-94bd-4b16-b7f5-714f580e71af.png)
참고 https://www.youtube.com/watch?v=96OEN2c28So

- 사전 순으로 다음에 오는 순열
 
- nCr = nPr/r! (nPr 펼치면 r개이다)
- 조합 특징
  - https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=vollollov&logNo=220919085017
