### ISSUE TITLE
배열(Array), 연결리스트(Linked List), 해시테이블(Hash Table)

### ISSUE THREAD

**Issue by kdomo** [Green-Record/algorithm-study#22]
#### 해시테이블을 사용한 집합과 맵 메서드
------
- 배열 문제
  - [브론즈3-BOJ 2953번 나는 요리사다](https://www.acmicpc.net/problem/2953)
  - [실버5-BOJ 11728번 배열 합치기](https://www.acmicpc.net/problem/11728)
  - [실버5-BOJ 2167번 2차원 배열의 합](https://www.acmicpc.net/problem/2167)
  - [실버5-BOJ 2563번 색종이](https://www.acmicpc.net/problem/2563)
  - [실버1-BOJ 11660번 구간 합 구하기5](https://www.acmicpc.net/problem/11660)

- 연결리스트 문제
  - [실버2-BOJ 1406번 에디터](https://www.acmicpc.net/problem/1406)
  - [실버2-BOJ 5397번 키로거](https://www.acmicpc.net/problem/5397)
  - [실버3-BOJ 1021번 회전하는 큐](https://www.acmicpc.net/problem/1021)
  - [실버4-BOJ 1158번 요세푸스 문제](https://www.acmicpc.net/problem/1158)
  - [골드4-BOJ 3190번 뱀](https://www.acmicpc.net/problem/3190)

- 해시테이블 문제
  - [BOJ 7785번 회사에 있는 사람](https://www.acmicpc.net/problem/7785)
  - [BOJ 9322번 철벽 보안 알고리즘](https://www.acmicpc.net/problem/9322)
  - [BOJ 10816번 숫자 카드2](https://www.acmicpc.net/problem/10816)
  - [BOJ 1764번 듣보잡](https://www.acmicpc.net/problem/1764)
  - [BOJ 11652번 카드](https://www.acmicpc.net/problem/11652)

**Comment by jinjinhee** [comment]
# 배열(Array)의 개념
배열(array)은 같은 타입의 변수들로 이루어진 유한 집합으로 정의됩니다.
배열을 구성하는 각각의 값을 배열 요소(element)라고 하며, 배열에서의 위치를 가리키는 숫자는 인덱스(index)라고 합니다.
파이썬에서 list 자료형
![image](https://user-images.githubusercontent.com/44153167/201473176-e7b5cd73-58cf-46f1-a8fe-eb7e94b15548.png)

# 배열 관련 메서드
```
삽입 - append(x) : 리스트의 맨 뒤에 x를 삽입한다. 시간복잡도 O(1)
삽입 - insert(i, x) : 리스트의 i번째 위치에 x를 삽입한다. 시간복잡도 O(n)
삭제 - pop() : 리스트의 맨 뒤 요소 1개를 삭제한다. 시간복잡도 O(1)
삭제 - pop(i) : 리스트의 i번째 요소 1개를 삭제한다. 시간복잡도 O(n)
삭제 - remove(x) : 리스트 요소들 중 x와 일치하는 것을 삭제한다. 시간복잡도 O(n)
삭제 - del(lst) : lst 리스트를 삭제한다. 시간복잡도 O(n)
검색 - index(x) : 리스트를 맨 앞부터 검색해서 x를 찾아 그 인덱스를 반환한다. 없을 경우 ValueError가 발생한다. 시간복잡도 O(n)
접근 - [i] : i번 인덱스의 요소에 접근할 수 있다. 만약 리스트의 길이보다 크거나 같은 숫자를 입력했을 경우 IndexError가 발생한다. 시간복잡도 O(n)
```

# 연결리스트(Linked List)의 개념
연결 리스트(Linked list)는 값, 리스트의 다음 노드에 대한 레퍼런스를 갖는 노드들로 이뤄진 선형 리스트이다. 마지막 노드는 레퍼런스로 null 값(None)을 가진다. 연결 리스트로 스택과 큐를 구현할 수도 있다.

파이썬에서는 연결리스트 자료형을 구현하려면 class를 이용하여 직접 구현 가능
![image](https://user-images.githubusercontent.com/44153167/201473190-588eba13-009e-4915-b533-0fd2e618d620.png)

```
class Node:
  def __init__(self, value=None, pointer=None):
    self.value = value
    self.pointer = pointer

  def getData(self):
    return self.value

  def getNext(self):
    return self.pointer
  
  def setData(self, value):
    self.value = value
  
  def setNext(self, pointer):
    self.pointer = pointer```
```
# 연결리스트(Linked List) 관련 메서드
매서드도 직접 구현 가능
```
class LinkedList:
    def __init__(self, data):
        self.head = Node(data)
    
    #헤더부터 탐색해 뒤에 새로운 노드 추가하기
    def append(self, data):
        cur = self.head
        while cur.next is not None:
            cur = cur.next
        cur.next = Node(data)
	
    #모든 노드 값 출력
    def print_all(self):
        cur = self.head
        while cur is not None:
            print(cur.data)
            cur = cur.next

   #노드 삭제
   def delete_node(self, index):
          if index == 0:
              self.head = self.head.next
              return
          node = self.get_node(index-1)
          node.next = node.next.next
```

# 해시테이블 Hash Table 개념
해시함수를 사용하여 변환한 값을 색인(index)으로 삼아 키(key)와 데이터(value)를 저장하는 자료구조

# 해시테이블을 사용한 집합과 맵 메서드
```
len(dict): 사전의 총 길이 (total length of Dictionary)
str(dict): 사전을 문자열로 반환 (string representation of a Dictionary)
type(variable): 입력 변수의 유형 반환 (returns the type of the passed variable)
dict.keys(): 사전의 키 목록
dict.values(): 사전의 값 목록
dict.items(): 사전의 (키, 값) 튜플 목록 
dict.clear(): 사전의 모든 {키, 값} 셋 제거
dict.copy(): 사전의 {키 : 값} 셋 복사
dict.fromkeys(seq, value): seq, value 셋으로 신규 사전 생성
dict.get(key, default=None): 키에 할당된 값 반환
dict.setdefault(key, default=None) : 키에 할당된 값 반환
dict.update(dict2): 기존 사전에 새로운 사전 dict2 추가
```

**Comment by kdomo** [comment]
### 배열(Array)
##### 배열(Array)이란?
- 배열은 연관된 데이터를 모아서 관리하기 위해서 사용되는 데이터 타입
- 여러 개의 데이터를 저장하기 위한 것
- 배열의 접근 시간복잡도 : $O(1)$
- 배열의 한계
  - 배열을 생성할 때 크기를 지정해주어야 한다(유동적이지 못함)
  - 원소 값을 중복 없이 관리하기 힘들다

##### 배열 관련 메서드
- 배열의 생성
```java
String[] fruits = new String[4];
```
- 배열에 값 대입
```java
fruits[0] = "apple";
fruits[1] = "grape";
fruits[2] = "melon";
fruits[3] = "banana";
```
</br>
</br>

### 연결리스트(Linked List)
##### 연결리스트(Linked List)란?
- 데이터와 다음데이터를 가지고 있는 포인터로 이루어져 있는 노드가 연결되어 있는 자료구조 형태
- 공간을 미리 할당하지 않아도 되기 때문에 데이터의 삽입, 삭제가 쉽다
- 데이터 탐색에 시간이 걸린다(index가 존재하지 않기 때문에)
##### 연결리스트(Linked List) 관련 메서드
- 자바 util클래스에서 제공하는 내장 라이브러리가 존재한다.
```java
import java.util.LinkedList;
LinkedList<Integer> numList = new LinkedList<Integer>();
```

|메서드|설명|
|---|---|
|add(데이터)|데이터 추가|
|add(인덱스번호, 데이터)|인덱스번호에 값 추가|
|addFirst(데이터)|맨 앞에 데이터 추가|
|addLast(데이터)|맨 뒤에 데이터 추가|
|remove(인덱스)|인덱스에 해당하는 데이터 삭제|
|clear()|모든 데이터 삭제|
|size()|사이즈 반환|
|get(인덱스)|인덱스에 해당하는 데이터 반환|
|contains(데이터)|해당하는 데이터가 존재하면 true 반환|
|indexOf(데이터)|해당하는 데이터가 몇 번째 인덱스에 존재하는지 반환 (없으면 -1 반환)|

</br>
</br>

### 해시테이블(Hash Table)
##### 해시테이블(Hash Table)이란?
- 키, 값을 대응시켜 저장하는 데이터 구조
- 키를 통해 해당 데이터를 빠르게 접근 가능
![image](https://user-images.githubusercontent.com/64088250/200511681-fdb51ff5-8726-4ed0-b8dc-74cb6546a6a9.png)

##### 해시테이블 메서드
- 자바 util클래스에서 제공하는 내장 라이브러리가 존재한다.
```java
import java.util.Hashtable;
Hashtable<KeyType, ValueType> ht = new Hashtable<>();
```

|메서드|설명|
|---|---|
|put(key, value)|key값에 대응되는 value 추가|
|remove(key)|key값에 대응되는 값 삭제|
|clear()|모든 값 삭제|
|size()|사이즈 반환|

- 출력하기
```java
for(Map.Entry<String, String> e : ht.entrySet())
        System.out.println("Key : " + e.getKey() + ", Value : " + e.getValue());
}
```

**Comment by jonggking** [comment]
# 배열(Array)의 개념
배열은 연속된 메모리 공간에 순차적으로 저장된 데이터 모음.
각 요소에 인덱스를 통해 접근 가능
   
# 배열 관련 메서드
연산 | 사용예시 | 시간복잡도 | 비고
-- | -- | -- | --
index | L[i] | O(1) | 
store | L[i] =x | O(1) | 
length | len(L) | O(1) | 
append | L.append(x) | O(1) | 
pop | L.pop() | O(1) | 가장 뒤 데이터 pop
pop | L.pop(i) | O(N) | 제거 후 한칸씩 당김
clear | L.clear | O(1) | L = []
slice | L[a:b] | O(b-a) | 
extend | L1.extend(L2) = L1+L2 | O(len(L2)) | 
construction | L1==L2 | O(N) | 전체 리스트 동일한지 확인
insert | L(i, x) | O(N) | 
delete | del L[i] | O(N) | 
containment | x in L <br> x not in L | O(N) | 
copy | L.copy() | O(N) | 
remove | L.remove(X) | O(N) | 
extreme value | min(L) <br> max(L) | O(N) | 
reverse | L.reverse() = L[::-1] | O(N) | 
itertation | for item in L: ~  | O(N) | 
sort | L.sort() / sorted(L) | O(NlogN) | 두번째 인자로 reversed=True
multiply |  k*L | O(kN) | 
count | L.count(x)  | O(N) | x 몇 개인지 세기
index | L.index(x)  | O(N) | 찾는 문자가 없는 경우에 ValueError 에러<br>문자열, 리스트, 튜플 자료형에서 사용 가능 딕셔너리 X

# 연결리스트(Linked List)의 개념
![image](https://user-images.githubusercontent.com/108375964/200515718-78dedf9c-bf52-4279-b7aa-323e62f71d03.png)
노드 안에 데이터와 다음 노드를 가리키는 포인터를 담아 한 줄로 연결된 자료구조.   마지막 요소에는 None(C에서의 NULL)이 있다. 이는 다음 값이 없다는 것을 의미하고 그 앞의 값이 마지막 값이 된다.

### 배열 vs 연결리스트
배열 | 연결리스트
-- | --
메모리 공간에 순차적으로 배치⇒ []로 상수시간 접근 가능 | 메모리상에서 흩어져 있어서 상수시간 접근이 불가능
 값과 값 사이에 새 값을 넣으려면 삽입한 값 이후의 모든 요소를 한 칸씩 이동해야 한다. <br>⇒ 삽입삭제 비용큼. | 중간에 새 노드를 넣고 다시 연결. 두 개의 링크 주소만 바꾸면 되므로 insert 작업에는 상수시간. 단, 교체해야할 노드를 알고 있을 때에 상수시간이다.   

# 연결리스트(Linked List) 관련 메서드
```
class Node:
  def __init__(self, key = None):
    self.key = key
    self.next = None
  def __str__(self):
    return str(self.key) # print(v.key) 대시 print(v)로 쓸 수 있다

class SinglyLinkedList:
  def __init__(self):
    self.head = None
    self.size = 0
  def __len__(self):
    return self.size
  def pushFront(self, key):
    new_node = Node(key)
    new_node.next = self.head;
    self.head = new_node
    self.size += 1
  def pushBack(self, key):
    v = Node(key)
    if len(self) == 0:
      self.head = v
    else:
      tail = self.head
      while tail.next != None:
        tail = tail.next
      tail.next = v
    self.size += 1

def popFront(self):
  if len(self) == 0:
    return None
  else:
    x = self.head
    key = x.key
    self.head = x.next
  self.size -= 1
  del x
  return key
```
# 해시테이블 Hash Table 개념
Key와 Value로 구성된 것.   
매우 빠른 평균 삽입, 삭제, 탐색 연산 제공

# 해시테이블을 사용한 집합과 맵 메서드
연산 | 사용예시 | 시간복잡도 | 비고
-- | -- | -- | --
Store | dict[k] = v | O(1) | 데이터 저장
Length | len(dict) | O(1) | 길이 출력
Delete | del dict[k] | O(1) | 요소 제거
get/setdefault | dict.get(k) | O(1) | key에 따른 value 확인
Pop | dict.pop(k) | O(1) | pop
Pop item | dict.popitem() | O(1) | 랜덤하게 선택해서 pop
Clear | dict.clear() | O(1) | similar to s = {} or = dict()
View | dict.keys() | O(1) | 키값 전체 목록
View | dict.values() | O(1) | value 값 전체 목록
View | dict.items() | <br> | value 값 전체 목록
Copy | dict.copy() | <br> | 복사
Construction | dict(...) | O(len(...)) | (key, value) 튜플 개수만큼
Iteration | for k in d: | O(N) | 전체 딕셔너리 순회

**Comment by thankyouthankyou** [comment]
**해시테이블**
Key 와 Value 값으로 된 쌍을 저장하는 자료구조
C++ 에서는 map, python 에서는 dictionary 사용
해시테이블 구현시 충돌이 일어나게 되면 changing 혹은 open addressing 을 통해 해결해야 한다
공간을 소비해서 접근 속도를 높일 때 사용한다
데이터 접근이 빈번하게 일어나지 않을 떄 사용한다.

#include<hash_map>
using namespace stdext;
hash_map<key 자료 타입, value 자료타입> 변수 이름;

begin - 첫번째 원소의 랜덤 반복자를 반환
clear - 저장한 모든 원소를 삭제
empty - 저장한 원소가 없으면 true 반환
end - 마지막 원소(미사용 영역)의 다음 반복자를 반환 
erase - 특정 위치의 원소나 지정 범위의 원소들을 삭제
find - key 와 연관된 원소의 반복자 반환
insert - 원소 추가

**Comment by josuehyeon** [comment]
배열(Array)의 개념 
배열 관련 메서드
<html>
<body>
<h4 style="box-sizing: border-box; margin: 15px 0px 15px 10px; padding: 0px; border: 0px; font-size: 18px; font-family: notokr; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">대표적인 Arrays 메소드</h4><p style="box-sizing: border-box; margin: 0px 0px 0px 10px; padding: 0px; word-break: break-all; font-family: notokr; font-size: 15px; line-height: 27px; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Arrays 클래스의 메소드는 매우 다양하며, 그중에서 많이 사용되는 메소드는 다음과 같습니다.</p>

메소드 | 설명
-- | --
static <T> List<T> asList(T... a) | 전달받은 배열을 고정 크기의 리스트(list)로 변환하여 반환함.
static int binarySearch(Object[] a, Object key) | 전달받은 배열에서 특정 객체를 이진 검색 알고리즘을 사용하여 검색한 후, 그 위치를 반환함.
static <T> T[] copyOf(T[] original, int newLength) | 전달받은 배열을 특정 길이의 새로운 배열로 복사하여 반환함.
static <T> T[] copyOfRange(T[] original, int from, int to) | 전달받은 배열의 특정 범위에 해당하는 요소만을 새로운 배열로 복사하여 반환함.
static boolean equals(Object[] a, Object[] a2) | 전달받은 두 배열이 같은지를 확인함.
static void fill(Object[] a, Object val) | 전달받은 배열의 모든 요소를 특정 값으로 초기화함.
static void sort(Object[] a) | 전달받은 배열의 모든 요소를 오름차순으로 정렬함.

<br class="Apple-interchange-newline">
</body>
</html>

연결리스트(Linked List)의 개념
연결리스트(Linked List) 관련 메서드
해시테이블 Hash Table 개념
해시테이블을 사용한 집합과 맵 메서드
