### ISSUE TITLE
스택(Stack), 큐(Queue), 덱(Deque), 우선순위 큐 (Priority Queue), 힙(Heap)

### ISSUE THREAD

**Issue by jonggking** [Green-Record/algorithm-study#26]
### 스택(Stack)
- 스택(Stack)의 개념
- 스택(Stack) 관련 메서드

## 큐(Queue)
- 큐(Queue)의 개념
- 큐(Queue) 관련 메서드

## 덱(Deque, Double-ended Queue)
- 덱(Deque, Double-ended Queue)의 개념
- 덱(Deque, Double-ended Queue) 관련 메서드

## 우선순위 큐 (Priority Queue)
- 우선순위 큐 (Priority Queue)의 개념
- 우선순위 큐 (Priority Queue) 관련 메서드

## 힙(Heap)
- 힙(Heap)의 개념
- 힙(Heap) 관련 메서드

--------------------------------------------------------

https://www.acmicpc.net/problem/10828
https://www.acmicpc.net/problem/9012
https://www.acmicpc.net/problem/10799
https://www.acmicpc.net/problem/10845

https://www.acmicpc.net/problem/11723
https://www.acmicpc.net/problem/11279
https://www.acmicpc.net/problem/1927

[프로그래머스]
스택/큐 6문제
https://school.programmers.co.kr/learn/courses/30/parts/12081
힙 3문제
https://school.programmers.co.kr/learn/courses/30/parts/12117

**Comment by jinjinhee** [comment]
# 스택(Stack)의 개념
스택은 가장 나중에 들어온 자료가 가장 먼저 처리되는 LIFO(Last-In-First-Out) 자료구조이다.
구멍이 하나밖에 없는 병이라고 생각하면 이해하기 쉽다.
![image](https://user-images.githubusercontent.com/44153167/201473147-867a1ac5-83f8-4cd0-9e87-9080565117d9.png)


## 스택(Stack) 관련 메서드
```
len(Stack)
Stack.pop()
Stack.append(e)
Stack[-1]
```

# 큐(Queue)의 개념
큐는 가장 나중에 들어온 자료가 가장 나중에 처리되는 FIFO(First-In-First-Out) 자료구조이다.
파이썬의 queue 라이브러리에는 앞에서 언급한대로 Queue(), LifoQueue(), PriorityQueue()가 존재
![image](https://user-images.githubusercontent.com/44153167/201473152-f5ec04e0-bd4f-4f87-85b1-07df980d5599.png)


## 큐(Queue) 관련 메서드
```
Queue.qsize()
Queue.empty()
Queue.full()
Queue.put(item, block=True, timeout=None)
Queue.put_nowait(item)
Queue.get(block=True, timeout=None)
Queue.get_nowait()
Queue.task_done()
Queue.join()
```
# 우선순위 큐 (Priority Queue)의 개념
우선순위 큐는 데이터를 추가한 순서대로 제거하는 선입선출(FIFO) 특성을 가진 일반적인 큐의 자료구조와 달리, 데이터 추가는 어떤 순서로 해도 상관이 없지만, 제거될 때는 **가장 작은 값**을 제거하는 독특한 특성을 지닌 자료구조입니다.
이 말은 내부적으로 데이터를 정렬된 상태로 보관하는 메커니즘이 있다는 뜻이고, 좀 더 구체적으로 얘기하면 heapq 모듈을 통해 구현
## 우선순위 큐 (Priority Queue) 관련 메서드

# 힙(Heap)의 개념
힙은 부모노드와 자식노드의 관계로 최대 힙, 최소 힙으로 나뉜다.
키 값의 대소관계는 부모노드와 자식노드 간에만 성립하며 형제 사이에는 성립하지 않을 수 있다.
최대 힙 : 부모노드 키 값 >= 자식노드 키 값. 뿌리노드가 항상 제일 큼
최소 힙 : 부모노드 키 값 <= 자식노드 키 값. 뿌리노드가 항상 제일 작음
배열에 있는 데이터의 최대값 또는 최소값을 찾으려면 O(n)이 걸리지만
힙에 있는 데이터의 최대값 또는 최소값을 찾으려면 O(logn)이 걸리므로 더 효율적이다. 
힙으로 구현된 이진트리구조는 배열로 저장된다.

## 힙(Heap) 관련 메서드
```
heapq.heappush(heap, item)
heapq.heappop(heap)
heapq.heappushpop(heap, item)
heapq.heapify(x)
heapq.heapreplace(heap, item)
heapq.merge(*iterables, key=None, reverse=False)
heapq.nlargest(n, iterable, key=None)
heapq.nsmallest(n, iterable, key=None)
```

```
파이썬에서 우선순위 큐 (Priority Queue)와 힙(Heapq)의 차이
Thread-Safe를 요구하는 상황에서는 PriorityQueue
Thread-Non-Safe 해도 된다면 heapq 를 사용하는 것이 옳다.
```

# 덱(Deque, Double-ended Queue)의 개념
덱(Dequeue)은 데이터 값을 저장하는 기본적인 구조로, 일차원의 선형 자료구조
덱은 스택(Stack)과 큐(Queue)의 연산을 모두 지원하는 자료구조로, 양 끝에서 모두 삽입과 삭제가 가능한 큐라고 생각하면 된다.
![image](https://user-images.githubusercontent.com/44153167/201473158-9ae0fba2-9786-4817-97df-e0bcb236b056.png)

## 덱(Deque, Double-ended Queue) 관련 메서드

```
append(x)
appendleft(x)
clear()
copy()
count(x)
extend(iterable)
extendleft(iterable)
index(x[, start[, stop]])
insert(i, x)
pop()
popleft()
remove(value)
reverse()
rotate(n=1)
maxlen
```

**Comment by kdomo** [comment]
### 스택(Stack)
##### 스택(Stack)이란?
![image](https://user-images.githubusercontent.com/64088250/201860845-d19651ce-b71f-4d0b-a74c-73346cafc9b2.png)

- 사전적 의미로 '쌓다', '더미' 라는 뜻
- 후입선출(선출후입) LIFO(Last In First Out)
  - 마지막에 들어온 데이터가 먼저 나가는 구조
- 스택의 push, pop 시간복잡도 : $O(1)$
- 스택의 생성
```java
Stack<Element> stack = new Stack<>();
```
|명령어|반환타입|설명
|---|---|---|
|`stack.push(1);`|`E`|stack에 값(1) 추가|
|`stack.pop();`|`E`|Top에 있는 데이터 한개 꺼냄|
|`stack.peek();`|`E`|Top에 있는 값을 보여줌(삭제X)|
|`stack.contains(1);`|`boolean`|stack에 1 포함여부 반환|
|`stack.size();`|`int`|stack 사이즈 반환|
|`stack.empty();`|`boolean`|stack이 비어있는지 여부 반환|
|`stack.clear();`|`void`|stack을 초기화 시켜줌|

</br>
</br>

### 큐(Queue)
##### 큐(Queue)란?
![image](https://user-images.githubusercontent.com/64088250/201860891-c4f7d78b-c0dd-4564-b742-7f4dd84b6138.png)

- 선입선출(First In First Out) 자료구조
  - 먼저 들어온 데이터가 먼저 나가는 구조
  - 입력 순서대로 데이터 처리가 필요할 때 사용 (BFS, 프린터 출력 대기열 등)
  - 큐의 생성
```java
Queue<Element> queue = new LinkedList<>();
```
|명령어|반환타입|설명
|---|---|---|
|queue.add(1); | boolean | queqe에 값 추가|
|queue.poll(); | E | front에 있는 값을 한개 꺼냄|
|queue.peek(); | E | front에 있는 값을 보여 줌(삭제X)|
|queue.contains(1); | boolean | queqe에 1 포함여부 반환|
|queue.size(); | int | queqe 사이즈 반환|
|queue.isEmpty(); | boolean | queqe가 비어있는지 여부 반환|
|queue.clear(); | void | qeuqe를 초기화 시켜줌|

<br/>
<br/>

### 데크(Deque)
##### 데크(Deque)란?
![image](https://user-images.githubusercontent.com/64088250/201863483-3926ff4a-40dc-478c-8856-f74bcacd99c1.png)

- 양쪽에서 삽입과 삭제가 모두 가능한 자료구조
- Stack과 Queue를 합친 상태
- 데크의 생성
```java
Deque deque = new ArrayDeque();
```

|명령어 | 반환타입 | 설명|
|-- | -- | --|
|deque.addFirst(1); | boolean | Rear(왼쪽)에 값 1 추가|
|deque.removeFirst(); | E | Rear(왼쪽)에 있는 값을 한개 꺼냄|
|deque.addLast(30); | void | Front(오른쪽)에 값 30 추가|
|deque.removeLast(); | E | Front(오른쪽)에 있는 값을 한개 꺼냄|
|deque.size(); | int | deque의 사이즈 반환|
|deque.contains(3); | boolean | deque에 3이 존재하는지 판단|
|deque.isEmpty(); | boolean | queqe가 비어있는지 여부 반환|
|deque.clear(); | void | qeuqe를 초기화 시켜줌|

<br/>
<br/>

### 우선순위 큐(Priority Queue)
##### 우선순위 큐(Priority Queue)란?
- 우선순위가 높은 데이터가 먼저 나옴
- 모든 데이터에 우선순위가 존재
- Dequeue시 우선순위가 높은 순으로 나감
- 우선순위가 같은 경우에는 FIFO
- 시간복잡도 : $O(NlogN)$
- 우선순위 큐 생성
```java
//낮은 숫자가 우선 순위인 int 형 우선순위 큐 선언
PriorityQueue<Integer> priorityQueueLowest = new PriorityQueue<>();

//높은 숫자가 우선 순위인 int 형 우선순위 큐 선언
PriorityQueue<Integer> priorityQueueHighest = new PriorityQueue<>(Collections.reverseOrder());
```

</br>
</br>

### 힙(Heap)
##### 힙(Heap)이란?
- 완전 이진 트리 형태의 일종
- 여러 개의 값들 중에서 최댓값이나 최솟값을 빠르게 찾아내도록 만들어진 자료구조
- 힙 트리에서는 중복된 값을 허용(이진 탐색 트리에서는 중복된 값을 허용하지 않는다.)
##### 힙(Heap)의 종류
- 최대 힙(max heap)
  - 부모 노드의 키 값이 자식 노드의 키 값보다 크거나 같은 완전 이진 트리
  - 부모 노드 key >= 자식노드 key
![image](https://user-images.githubusercontent.com/64088250/201868134-9cbc5d35-737a-4f1d-aaea-ed76717c38ea.png)

- 최소 힙(min heap)
  - 부모 노드의 키 값이 자식 노드의 키 값보다 작거나 같은 완전 이진 트리
  - 부모 노드 key <= 자식 노드 key
![image](https://user-images.githubusercontent.com/64088250/201868268-8c47de22-d8f2-42f9-9f1f-d4e1bde8abf0.png)

**Comment by jonggking** [comment]
# 스택(Stack)
![image](https://user-images.githubusercontent.com/108375964/201888643-8158d55c-636c-4a5c-836e-3e675a1de7d3.png)

```
삽입: push, 맨 위에 값 삭제: pop, 맨위에 값 봄: top, 길이: len =>모두 상수시간인 자료구조.
##(리스트- 삽입: ppend, 삭제:pop)
class Stack:
		def __init__(self):
			self.items = []		
		def push(self, val):
			self.items.append(val)
		def pop(self):
			try
				return self.items.pop()
			except IndexError:
					print("Stack is empty")
		def top(self):
			try
				return self.items[-1]
			except IndexError:
					print("Stack is empty")
		def __len__(self):
			return len(self.items)
```
# 큐(Queue)
![image](https://user-images.githubusercontent.com/108375964/201889979-ad98c2b3-6d20-44ed-a1a2-5f69f8c0b8cc.png)

# 덱(Deque, Double-ended Queue)
![image](https://user-images.githubusercontent.com/108375964/201892655-27c99a42-5408-4f1d-8b43-08bd54cec9a7.png)
stack + queue   

## 덱(Deque, Double-ended Queue) 관련 메서드
dq=deque() # 덱 생성
dq.append() # 덱의 가장 오른쪽에 원소 삽입
dq.popleft() # 가장 왼쪽 원소 반환
dq.appendleft() # 덱의 가장 왼쪽에 원소 삽입
dp.pop() # 가장 오른쪽 원소 반환
dp.clear() # 모든 원소 제거
dp.copy() # 덱 복사
dp.count(x) #x와 같은 원소의 개수를 계산

# 우선순위 큐 (Priority Queue)
: 우선순위가 높은 데이터가 먼저 나가는 자료구조 => 주로 힙으로 구현됨

# 힙(Heap)
:완전 이진 트리의 일종으로 우선순위 큐를 위하여 만들어진 자료구조이다.
여러 개의 값들 중에서 최댓값이나 최솟값을 빠르게 찾아내도록 만들어진 자료구조이다.
힙은 일종의 반정렬 상태(느슨한 정렬 상태) 를 유지한다.
큰 값이 상위 레벨에 있고 작은 값이 하위 레벨에 있다는 정도
간단히 말하면 부모 노드의 키 값이 자식 노드의 키 값보다 항상 큰(작은) 이진 트리를 말한다.
힙 트리에서는 중복된 값을 허용한다. (이진 탐색 트리에서는 중복된 값을 허용하지 않는다.)
https://gmlwjd9405.github.io/2018/05/10/data-structure-heap.html

````
> H[k]의 왼쪽 자식노드: H[2 * k + 1]
> 
> 
> H[k]의 오른쪽 자식노드: H[2 * k + 2]
> 
> H[k]의 부모노드: H[(k - 1) // 2]
> 

모두 상수시간에 계산 가능. 

단점: 비어있는 곳을 None으로 표시하기 위해 자리를 차지하는 불필요한 공간 생김. 트레이드오프. 레벨을 꽉꽉 채워주면 이 낭비를 없앨 수 있다. 꽉꽉 채워둔 이진트리를 힙이라고 부른다.
`````
## 힙(Heap) 관련 메서드
- `make_heap`: O(n), O(nlogN)
- `insert`: O(logN)
- `find_max`: O(1)
- `delete_max`: O(logN)
- `heapify_down`: O(h) = O(logN)
- `heapify_up`: O(h) = O(logN)

힙에는 `search` 함수가 없다. 정리가 되어 있는 게 아니다보니 알 방법이 없어서 무조건 모두 탐색해야한다. `search`는 효율이 없고,  `insert`, `find_max`, `delete_max`를 이용하는 경우에 힙이 좋다.
`find_min`과 `delete_min`을 갖는 힙인 min_heap을 만들 수 있다.
정렬을 하는 경우, 힙 소트를 할 수 있다. `make_heap()`은 O(nlogN)이므로 정렬 후 `delete_max()`의 반환과 유사한 형식을 이용해 할 수 있다.
