### ISSUE TITLE
정렬, 이진 탐색, 투 포인터

### ISSUE THREAD

**Issue by kdomo** [Green-Record/algorithm-study#30]
[정렬]
- [프로그래머스 - K번째 수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
- [프로그래머스 - 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
- [프로그래머스 - H-index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
- [백준 - 좌표압축](https://www.acmicpc.net/problem/18870)

[이진 탐색]
- [백준 - 예산](https://www.acmicpc.net/problem/2512)
- [백준 - 랜선자르기](https://www.acmicpc.net/problem/1654)
- [백준 - 나무자르기](https://www.acmicpc.net/problem/2805)
- [백준 - 용돈관리](https://www.acmicpc.net/problem/6236)
- [백준 - 기타 레슨](https://www.acmicpc.net/problem/2343)

[투 포인터]
- [백준 - 수들의 합2](https://www.acmicpc.net/problem/2003)
- [백준 - N번째 큰 수](https://www.acmicpc.net/problem/2075)
- [프로그래머스 - 구명보트](https://school.programmers.co.kr/learn/courses/30/lessons/42885)
- [백준 - 회전초밥](https://www.acmicpc.net/problem/2531)

**Comment by jinjinhee** [comment]
# 정렬
컴퓨터 과학과 수학에서 정렬 알고리즘(sorting algorithm)이란 원소들을 번호순이나 사전 순서와 같이 일정한 순서대로 열거하는 알고리즘이다.

1. 선택 정렬 (n^2, n^2, n^2)
이중 for 루프를 이용해 자료구조를 정렬하는 정렬 방식
```
def solution(l):
  for i in range(len(l)-1):
    min_idx = i
    for j in range(i+1, len(l)):
      if l[min_idx] > l[j]:
        min_idx = j
    l[i], l[min_idx] = l[min_idx], l[i]
```
2. 삽입 정렬 (n, n^2, n^2)
정렬 범위를 1칸씩 확장해나가면서 새롭게 정렬 범위에 들어온 값을 기존 값들과 비교하여 알맞은 자리에 꼽아주는 알고리즘
```
def solution(l):
  for i in range(1, len(l)):
    key = l[i] 
    j = i - 1
    while j >= 0 and l[j] > key:
      l[j+1] = l[j]
      j -= 1
    
    l[j+1] = key
```
3. 거품 정렬 (n, n^2, n^2)
리스트 요소의 이웃 요소와 비교(인접한 두 항목을 비교)해 이웃 요소와 정렬이 안 되어 있을 경우 서로 자리를 바꿔주는 방식의 정렬
```
def solution(l):
  for i in range(len(l)-1):
    for j in range(len(l)-1-i):
      if l[j] > l[j+1]:
        l[j], l[j+1] = l[j+1], l[j]
```
4. 병합 정렬 (nlogn, nlogn, nlogn)
기법과 재귀 알고리즘을 이용해서 정렬 알고리즘입니다. 즉, 주어진 배열을 원소가 하나 밖에 남지 않을 때까지 계속 둘로 쪼갠 후에 다시 크기 순으로 재배열 하면서 원래 크기의 배열로 합치는 알고리즘
```
def merge_sort(arr):
    if len(arr) < 2:
        return arr

    mid = len(arr) // 2
    low_arr = merge_sort(arr[:mid])
    high_arr = merge_sort(arr[mid:])

    merged_arr = []
    l = h = 0
    while l < len(low_arr) and h < len(high_arr):
        if low_arr[l] < high_arr[h]:
            merged_arr.append(low_arr[l])
            l += 1
        else:
            merged_arr.append(high_arr[h])
            h += 1
    merged_arr += low_arr[l:]
    merged_arr += high_arr[h:]
    return merged_arr
```
5. 퀵 정렬 (nlogn, nlogn, n^2)
병합 정렬이 리스트의 중간 인덱스를 기준으로 좌우로 그룹을 나눠 계속 쪼개나가 정렬하는 방식이라면 퀵 정렬은 피벗값(pivot)을 두고 그 피벗값과 다른 값들을 비교해 값들을 바꿔나가는 방식
```
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    lesser_arr, equal_arr, greater_arr = [], [], []
    for num in arr:
        if num < pivot:
            lesser_arr.append(num)
        elif num > pivot:
            greater_arr.append(num)
        else:
            equal_arr.append(num)
    return quick_sort(lesser_arr) + equal_arr + quick_sort(greater_arr)
```
6. 힙 정렬 (nlogn, nlogn, nlogn)
힙의 루트에 가장 크거나 작은 값이 들어간다는 점을 이용해 정렬하는 알고리즘
```
import heapq

def heap_sort(lst):
  h = []
  for val in lst:
    heapq.heappush(h, val)
  return [heapq.heappop(h) for _ in range(len(h))]
```

# 이진 탐색
데이터가 정렬돼 있는 배열에서 특정한 값을 찾아내는 알고리즘이다. 배열의 중간에 있는 임의의 값을 선택하여 찾고자 하는 값 X와 비교한다. X가 중간 값보다 작으면 중간 값을 기준으로 좌측의 데이터들을 대상으로, X가 중간값보다 크면 배열의 우측을 대상으로 다시 탐색한다. 동일한 방법으로 다시 중간의 값을 임의로 선택하고 비교한다. 해당 값을 찾을 때까지 이 과정을 반복
```
def binary_search(target, data):
    data.sort()
    start = 0
    end = len(data) - 1

    while start <= end:
        mid = (start + end) // 2

        if data[mid] == target:
            return mid
        elif data[mid] < target:
            start = mid + 1
        else:
            end = mid -1

    return None
```
# 투 포인터
투 포인터 알고리즘은 리스트에 순차적으로 접근해야 할 때 두 개의 점의 위치를 기록하면서 처리하는
알고리즘
```
def binary_search(target, array):

  front = 0
  rear = 0

  while rear < len(array):
      if sum(array[front:rear]) < target:
          rear += 1
      elif sum(array[front:rear]) > target:
          front += 1
      elif sum(array[front:rear]) == target:
          print(array[front:rear])
          rear += 1
```
