### ISSUE TITLE
분할 정복(Divide and Conquer) 동적 프로그래밍(Dynamic Programming)

### ISSUE THREAD

**Issue by kdomo** [Green-Record/algorithm-study#34]
## 분할 정복(Divide and Conquer)
- [행렬 곱셉](https://www.acmicpc.net/problem/2740)
- [색종이 만들기](https://www.acmicpc.net/problem/2630)
- [종이의 개수](https://www.acmicpc.net/problem/1780)
- [쿼드트리](https://www.acmicpc.net/problem/1992)
- [곱셈](https://www.acmicpc.net/problem/1629)

## 동적 프로그래밍(Dynamic Programming)
- [BOJ 2748 피보나치 수 2](https://www.acmicpc.net/problem/2748)
- [BOJ 1463 1로 만들기](https://www.acmicpc.net/problem/1463)
- [BOJ 9095 123 더하기](https://www.acmicpc.net/problem/9095)
- [BOJ 2579 계단 오르기](https://www.acmicpc.net/problem/2579)    
- [BOJ 11276 2xn 타일링](https://www.acmicpc.net/problem/11726)

**Comment by jinjinhee** [comment]
# 분할 정복(Divide and Conquer)
![image](https://user-images.githubusercontent.com/44153167/204829678-6890c0b9-a501-4812-8943-006af0b6f258.png)
그림에서와 같이 분할 정복은 상단에서 분할하고 중앙에서 정복하고 하단에서 조합(Combine)하는 형태로 도식화 할 수 있다.
분할: 문제를 더이상 분할할 수 없을 때까지 동일한 유형의 여러 하위 문제로 나눈다.
정복: 가장 작은 단위의 하위 문제를 해결하여 정복한다.
조합: 하위 문제에 대한 결과를 원래 문제에 대한 결과로 조합한다.

분할 정복법은 재귀적으로 자신을 호출하면서 그 연산의 단위를 조금씩 줄어가는 방식
분할한 문제가 간단한 해결 조건을 만족할 때까지 문제를 쪼개고 쪼개서 값을 구하는 방식

## 장점
문제를 나눔으로써 어려운 문제를 해결할 수 있다는 장점이 있다. 그리고 이 방식이 그대로 사용되는 효율적인 알고리즘들도 여럿 있으며 문제를 나누어 해결한다는 특징상 병렬적으로 문제를 해결하는 데 큰 강점이 있다.
## 단점
함수를 재귀적으로 호출한다는 점에서 함수 호출로 인한 오버헤드가 발생하며, 스택에 다양한 데이터를 보관하고 있어야 하므로 스택 오버플로우가 발생하거나 과도한 메모리 사용을 하게 되는 단점이 있다 가장 중요한 것은 이 알고리즘의 핵심인 분할한 문제가 간단해질때가 어떤 것이냐에 따라 알고리즘의 퍼포먼스가 생각보다 꽤 차이나게 된다는 것이다

# 동적 프로그래밍(Dynamic Programming)
큰 문제를 작게 나누고, 같은 문제라면 한 번씩만 풀어 문제를 효율적으로 해결하는 알고리즘 기법
메모리 공간을 약간 더 사용하면 연산 속도를 비약적으로 증가시키는 알고리즘

## 탑 다운(메모이제이션)(DP 테이블)
재귀 형태로 구현이 되기 때문에 점화식을 한 눈에 보기 쉽게 표현할 수 있습니다. 하지만 재귀라는 방식이 시간이나 메모리 효율상 좋지 않다는 단점
```
n=int(input())
ans=[0,1,2,4]+[0]*(n-3)
for i in range(4,n+1):
    ans[i]=ans[i-1]+ans[i-2]+ans[i-3]
for _ in range(n):
    print(ans[int(input())])
```
## 바텀 업
시간과 메모리 상 효율적이라는 장점
```
n = int(input())
def sol(n) :
    if n == 1 :
        return 1
    elif n == 2 :
        return 2
    elif n == 3 :
        return 4
    else :
        return sol(n-1) + sol(n-2) + sol(n-3)

for _ in range(n) :
    print(ans[int(input())])
```
